apiVersion: apps/v1
kind: Deployment
metadata:
  name: lbg-python
  labels:
    app: lbg-python
  spec:
    strategy:
      rollingUpdate:
        maxSurge: 50%
        maxSurge: 50%
     replicas: 2
     selector:
      matchLabels:
        app: lbg-python
     template:
      metadata:
        labels:
          app: lbg-python
      spec:
        containers:
          - image: gcr.io/lbg-mea-11/lbg-app-mj:v1
            name: lbg-python
            ports:
              - containerPort: 5000
            env:
              PORT: 5000
